### ISSUE TITLE
ERROR: Invalid client.

### ISSUE THREAD

**Issue by lonlyman** [spaze/oprah-proxy#20]
ERROR: Invalid client.

{"return_code":{"610":"This device cannot be registered: the number of allowed devices has been reached."},"data":{}}

**Comment by MarvinFS** [comment]
the same here cant connect anymore, although it just shows me this

`2017-05-18 18:36:20,365 DEBUG    +++==+======+++                           ==================
2017-05-18 18:36:20,365 DEBUG    ~~~~==========~  EVERYBODY GETS A PROXY!  ~~~~~~~~~~~~~~~~~~
2017-05-18 18:36:20,365 DEBUG    ~~~~~~~~~~~===~                           ~~~~~~~~~~~~~~~~~~
2017-05-18 18:36:20,365 DEBUG    =============++===:::::::::::::::::::::~~~~~~~~~~~~~~~~~~~:~
2017-05-18 18:36:20,365 DEBUG    https://github.com/spaze/oprah-proxy :::==~=~~~~~~~~=~~~~~~~
2017-05-18 18:36:20,365 DEBUG    Call register_subscriber
2017-05-18 18:36:20,365 DEBUG    Your SurfEasy email: fc9545d5-de80-49b1-9b2c-2048ff608616@se0310.surfeasy.vpn
2017-05-18 18:36:20,366 DEBUG    Your SurfEasy password: 836277ac-72b1-456c-a24b-894fc952c041
2017-05-18 18:36:20,366 DEBUG    Your SurfEasy password hash: 351AC071CB04F71A9D1265336A36A2148B572B93
2017-05-18 18:36:20,366 DEBUG    These are not the credentials you are looking for (you won't probably need these, ever)
2017-05-18 18:36:20,388 DEBUG    Starting new HTTPS connection (1): api.surfeasy.com
2017-05-18 18:36:21,403 DEBUG    https://api.surfeasy.com:443 "POST /v2/register_subscriber HTTP/1.1" 200 None
2017-05-18 18:36:21,403 DEBUG    ERROR: Invalid client.
`

**Comment by lonlyman** [comment]
any hope to fix this ?

Regards.

___________________________________________

*Linda Hoxman*
*instaRanker <https://www.instaranker.com> Support Team.*

**Comment by lonlyman** [comment]
we have to find an automatic way to know this client id

**Comment by MarvinFS** [comment]
opera works though in vpn mode though. in the same county it's NL now

**Comment by lonlyman** [comment]
No it is still same old way , but they change the way you got the auth code !

**Comment by AgapovAlexsey** [comment]
new opera using v4 API

**Comment by lonlyman** [comment]
i have an old Opera And VPN is working just fine i mean the proxy !
so it is not a new version problem

**Comment by AgapovAlexsey** [comment]
old Opera using method "Login".

**Comment by lonlyman** [comment]
> old Opera using method "Login".
Well my it seems new 44.0.2510.1449 (PGO) - Opera is up to date!

**Comment by lonlyman** [comment]
SO there is NO way ?

**Comment by lonlyman** [comment]
@AgapovAlexsey  You mean to get the Auth info correct ?
because i can login to the proxy using the ols username:password !

but i can get a new one !

**Comment by AgapovAlexsey** [comment]
I rewrote the code in C # 2 months ago. And it worked until yesterday. Now I'm getting an Invalid client error. I tried to register as an Android client and got anyway "Invalid client"
Now I have Opera 45.0.2552.635 and it already uses the 4th version of the API

**Comment by lonlyman** [comment]
@AgapovAlexsey so what is our options ?
I made same things but in php !! and i have same as you! well definitely there is a way !

**Comment by lonlyman** [comment]
@AgapovAlexsey  , well it seem there is no one care ! any way 

i did decompile the opera vpn and i note : 

```
 private static final String API_KEY = "2D67631A124F7AE10629ACA9ACA5AB21D67D30BDF6CF11C0B78735527FDF4DCA";
  private static final String CLIENT_TYPE = "se0312";
  private static final String DNSSEC_ROOT_KEY = "root.key";
  private static final String STAGING_API_KEY = "0DE45CA1DA7E3F3374724B00D7AFCC892DC04314BB6EDD972A8E65C2BC6C1A9A";

```

**Comment by AgapovAlexsey** [comment]
@lonlyman you can install virtal andorid machine and handl traffic with Fiddler?

**Comment by lonlyman** [comment]
Will to be honest , i can not download VM now the net speed is 10kbs ! the atlantic cable is damaged! LOL

We have to find a way !!!!

BTW ,   Fiddler will not help ! **ben there done that !**

**Comment by lonlyman** [comment]
@AgapovAlexsey  we need the other of the script Mr @spaze to be with us ! it seem he is sleeping :) LOL

**Comment by spaze** [comment]
Opera has switched to API v4 which uses SHA-256 HTTP Digest Authentication. To calculate that a password is needed. That password cannot be captured by sniffing traffic, it's not transmitted. I've opened #21 in case anyone's able to figure out the password.

**Comment by lonlyman** [comment]
@spaze , hello 
I am beshoo who mailed you :)
any way what should i look on the decompiled APK ? i have it all ! anything (keyword) to search ?

**Comment by spaze** [comment]
The Android app doesn't use the v4 API yeat, I think.

**Comment by lonlyman** [comment]
Then how t works !

Regards.

___________________________________________

*Linda Hoxman*
*instaRanker <https://www.instaranker.com> Support Team.*

**Comment by lonlyman** [comment]
@spaze 

Please have a look : 

> $device_hash = '4BE7D6F1BD040DE45A371FD831167BC108554111';
> $apikey = '2D67631A124F7AE10629ACA9ACA5AB21D67D30BDF6CF11C0B78735527FDF4DCA';
> $client_type = 'se0307';

HTTP/1.0 200 OK
```

HTTP/1.1 200 OK
Server: nginx/1.12.0
Date: Fri, 19 May 2017 04:02:07 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 200 OK
X-UA-Compatible: IE=Edge,chrome=1
ETag: "43f3d56b6d9f5a5f571592b807546469"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: subscriber_credentials=1d7878737b0ce67dc3d1655083f4fb9cc9807c20753f979ee5fc8e0d640a36d3548138cc8cab6d55df159c2be904ec39634b807aeab830c7d8824b267a81081a%3A%3A; domain=.surfeasy.com; path=/; secure; HttpOnly
Set-Cookie: api_session=BAhJIgGvZXlKcFpDSTZORGM0TWpNek5ETXNJbTltSWpvM056YzJNREF3TENKMGF5STZJamt6TURjeE1EWTFZell6ClpXWmxNR0kwT0dVNU1XRmhOVEV6WkdZMllUSXlZMlJoWVRFM016bGtaV1E0TmpaaE0yVmxNRFpoT0dJeApaR0V5TkdNeU5tRWlMQ0owYlNJNklqSXdNVGN0TURndE1UZFVNRFE2TURJNk1EZGFJbjA9CgY6BkVG--2d414291713c29a957f654834c38e46e3630ee61; domain=.surfeasy.com; path=/; expires=Thu, 17-Aug-2017 04:02:07 GMT; HttpOnly
Set-Cookie: _proxy_manager_session31=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiJWMxNTgxOWEwM2E1M2FjZmFiOWFhMmU0NjFjN2EyNTRmBjsAVEkiG3N1YnNjcmliZXJfY3JlZGVudGlhbHMGOwBUSSIBgDFkNzg3ODczN2IwY2U2N2RjM2QxNjU1MDgzZjRmYjljYzk4MDdjMjA3NTNmOTc5ZWU1ZmM4ZTBkNjQwYTM2ZDM1NDgxMzhjYzhjYWI2ZDU1ZGYxNTljMmJlOTA0ZWMzOTYzNGI4MDdhZWFiODMwYzdkODgyNGIyNjdhODEwODFhBjsAVEkiHnN1YnNjcmliZXJfY3JlZGVudGlhbHNfaWQGOwBUaQTvudkC--daa7843a1845f2277d68b28c0d0e6b50a7839efc; domain=.surfeasy.com; path=/; secure; HttpOnly
X-Request-Id: b0a36b7e4c273cf707ed6ae2047fcb71
X-Runtime: 0.570619
X-Rack-Cache: invalidate, pass

{"return_code":{"0":"OK"},"data":{}}<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
  </style>
</head>

<body>
  <!-- This file lives in public/500.html -->
  <div class="dialog">
    <h1>We're sorry, but something went wrong.</h1>
    <p>We've been notified about this issue and we'll take a look at it shortly.</p>
  </div>
</body>
</html>

```

**Comment by lonlyman** [comment]
on your script : 

```
2017-05-19 04:31:15,434 DEBUG    https://github.com/spaze/oprah-proxy :::==~=~~~~~~~~=~~~~~~~
2017-05-19 04:31:15,434 DEBUG    Call register_subscriber
2017-05-19 04:31:15,435 DEBUG    Your SurfEasy email: 3d7de6b6-752b-4858-8626-b0b17e5e732c@se0307.surfeasy.vpn
2017-05-19 04:31:15,435 DEBUG    Your SurfEasy password: 992ac142-5a48-436b-80bb-9f8d96040a47
2017-05-19 04:31:15,435 DEBUG    Your SurfEasy password hash: FD646687BF7813281BE51B00D0372AC39074C9F1
2017-05-19 04:31:15,435 DEBUG    These are not the credentials you are looking for (you won't probably need these, ever)
2017-05-19 04:31:15,443 DEBUG    Starting new HTTPS connection (1): api.surfeasy.com
2017-05-19 04:31:16,620 DEBUG    https://api.surfeasy.com:443 "POST /v2/register_subscriber HTTP/1.1" 200 None
2017-05-19 04:31:16,624 DEBUG    Subscriber registered
2017-05-19 04:31:16,624 DEBUG    Call register_device
2017-05-19 04:31:17,148 DEBUG    https://api.surfeasy.com:443 "POST /v2/register_device HTTP/1.1" 500 728
Traceback (most recent call last):
  File "./proxy.py", line 141, in <module>
    op.register_device()
  File "./proxy.py", line 73, in register_device
    result = self.post('/v2/register_device', data)
  File "./proxy.py", line 42, in post
    headers=headers).json()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/download/Python-3.5.0/Lib/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/download/Python-3.5.0/Lib/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/download/Python-3.5.0/Lib/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
root@server [/download]#

```

**Comment by lonlyman** [comment]
@spaze 
I found this script 
https://milankragujevic.com/uploads/oprahProxy.py.txt

and i set 

$device_hash = '4BE7D6F1BD040DE45A371FD831167BC108554111';
$apikey = '2D67631A124F7AE10629ACA9ACA5AB21D67D30BDF6CF11C0B78735527FDF4DCA';
$client_type = 'se0307';

it rach this : 
I dont need the proxy ip address i just need the login and password!
```

2017-05-19 04:34:16,441 DEBUG    Call register_subscriber
2017-05-19 04:34:16,442 DEBUG    Your SurfEasy email: e5ad38ad-b5b4-4afc-b90d-3e064053be98@se0307.surfeasy.vpn
2017-05-19 04:34:16,442 DEBUG    Your SurfEasy password: 54094f11-093d-4597-9070-57d5199a557a
2017-05-19 04:34:16,442 DEBUG    Your SurfEasy password hash: 74AA9E83E8C8F53DD67F60B3296C5FB0E061451D
2017-05-19 04:34:16,442 DEBUG    These are not the credentials you are looking for (you won't probably need these, ever)
2017-05-19 04:34:16,450 DEBUG    Starting new HTTPS connection (1): api.surfeasy.com
2017-05-19 04:34:17,475 DEBUG    https://api.surfeasy.com:443 "POST /v2/register_subscriber HTTP/1.1" 200 None
2017-05-19 04:34:17,479 DEBUG    Subscriber registered
2017-05-19 04:34:17,479 DEBUG    Call register_device
2017-05-19 04:34:18,067 DEBUG    https://api.surfeasy.com:443 "POST /v2/register_device HTTP/1.1" 200 None
2017-05-19 04:34:18,069 DEBUG    Device id: se0307-9bed53b37b791f4393d7d68
2017-05-19 04:34:18,069 DEBUG    Device registered
2017-05-19 04:34:18,069 DEBUG    Call geo_list
2017-05-19 04:34:18,290 DEBUG    https://api.surfeasy.com:443 "POST /v2/geo_list HTTP/1.1" 200 None
2017-05-19 04:34:18,292 INFO     Supported country: CA Canada
2017-05-19 04:34:18,292 INFO     Supported country: US United States
2017-05-19 04:34:18,292 INFO     Supported country: DE Germany
2017-05-19 04:34:18,292 INFO     Supported country: NL Netherlands
2017-05-19 04:34:18,292 INFO     Supported country: SG Singapore
2017-05-19 04:34:18,293 DEBUG    Geo list fetched
2017-05-19 04:34:18,293 DEBUG    Call discover CA
2017-05-19 04:34:18,398 DEBUG    https://api.surfeasy.com:443 "POST /v2/discover HTTP/1.1" 200 None
2017-05-19 04:34:18,399 DEBUG    ERROR: Invalid client.

```

**Comment by lonlyman** [comment]
I believe /v2/ still valable somehow ! since my opera is working just fine but i am unable to get the info from it !

**Comment by spaze** [comment]
> I found this script
> https://milankragujevic.com/uploads/oprahProxy.py.txt

This is actually my script stripped down of some output.

**Comment by spaze** [comment]
```
$apikey = '2D67631A124F7AE10629ACA9ACA5AB21D67D30BDF6CF11C0B78735527FDF4DCA';
$client_type = 'se0307';
```

After some small updates this seems to work, thanks.

If your business depends on these proxies and on this script I'd strongly suggest to stop using it as they might stop working at any time. And the trend is they will.

**Comment by spaze** [comment]
> I believe /v2/ still valable somehow ! since my opera is working just fine but i am unable to get the info from it !

Yes API v2 is still available, it's just being phased out.

**Comment by lonlyman** [comment]
Well it is 100% depend on it . and i will pay to crack opera , which my
target !
i am ready to pay you if you like to work on this .

Any way did you update your script ?

Regards.

___________________________________________

*Linda Hoxman*
*instaRanker <https://www.instaranker.com> Support Team.*

**Comment by lonlyman** [comment]
try the proxy username and password ,itdos not works
Authentication credentials required.

Regards.

___________________________________________

*Linda Hoxman*
*instaRanker <https://www.instaranker.com> Support Team.*

**Comment by spaze** [comment]
Feel free to figure it out and submit a pull request, I'll be more than happy to include it. Thanks!

**Comment by lonlyman** [comment]
Well i am not a python programmer , i don't know how to  figure it out! it
seems networking connection or some thing , i think you have to check an
old version of opera, you can find the old version of opera on the opera
folder in your /programfile

Regards.

___________________________________________

*Linda Hoxman*
*instaRanker <https://www.instaranker.com> Support Team.*

**Comment by AgapovAlexsey** [comment]
@lonlyman you can get correct response from "discover" ? i recive only for "NL" country

**Comment by lonlyman** [comment]
Well , i just got a good replay but when i try the username:password it
said it is not correct !

We have to work all on this ! to solve it for good !

@spaze : i know (As written in the README, *this is just for research
purposes, to study how things work*.)

But we love this and we don't want to stop and see opera enjoy proxy and as
you said on the web site everyone  should have a proxy .

You start this project , and we support you ! let's do our best to make it
works regardless anything .

and i am ready to support your paypal account :)

**Comment by spaze** [comment]
@AgapovAlexsey See https://github.com/spaze/oprah-proxy/commit/119a29dfbf70cb41ea8a8c79650465a2bf85f4c0 The discover call is broken and was removed.

**Comment by spaze** [comment]
> i think you have to check an old version of opera, you can find the old version of opera on the opera
folder in your /programfile

I used to update the script with API keys from older versions of Opera, no need to do it again.

**Comment by lonlyman** [comment]
Then why it is not working the login ! while in the old opera i can use the VPN , i think it is some header problem ! true?

**Comment by spaze** [comment]
Using VPN and generating credentials are two different things.

Again, if you need commercial support for your business, buy a VPN subscription.

**Comment by spaze** [comment]
I've locked the conversation now. Feel free to submit a pull request or a bug with a solution. Thanks!
